"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-01 22:13:40.962599

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organization_id', 'key', 'endpoint')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_run_at', 'jobs', ['status', 'run_at'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_table('domains',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('inbound_status', sa.String(length=30), nullable=False),
    sa.Column('outbound_status', sa.String(length=30), nullable=False),
    sa.Column('spf_status', sa.String(length=30), nullable=False),
    sa.Column('dkim_status', sa.String(length=30), nullable=False),
    sa.Column('dmarc_status', sa.String(length=30), nullable=False),
    sa.Column('mx_status', sa.String(length=30), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_domains_organization_id'), 'domains', ['organization_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_org_created', 'events', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_events_resource_created', 'events', ['resource_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('provider_accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_accounts_organization_id'), 'provider_accounts', ['organization_id'], unique=False)
    op.create_table('inboxes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('domain_id', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_mode', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inboxes_address_active', 'inboxes', ['address'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_inboxes_expires_active', 'inboxes', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_inboxes_org_status', 'inboxes', ['organization_id', 'status'], unique=False)
    op.create_table('inbound_ingests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('inbox_id', sa.String(length=40), nullable=True),
    sa.Column('bounce_message_id', sa.String(length=40), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mail_from', sa.String(length=320), nullable=False),
    sa.Column('rcpt_to', sa.String(length=320), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message_id', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_ingests_organization_id'), 'inbound_ingests', ['organization_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('inbox_id', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('subject_normalized', sa.Text(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_inbox_last', 'threads', ['inbox_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_threads_organization_id'), 'threads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_threads_subject_normalized'), 'threads', ['subject_normalized'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('inbox_id', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_organization_id'), 'webhooks', ['organization_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('inbox_id', sa.String(length=40), nullable=False),
    sa.Column('thread_id', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('from_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('to_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cc_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bcc_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reply_to_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('internet_message_id', sa.String(length=998), nullable=False),
    sa.Column('in_reply_to', sa.String(length=998), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_storage_key', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'inbox_id', 'internet_message_id', name='uq_messages_org_inbox_mid')
    )
    op.create_index('ix_messages_inbox_created', 'messages', ['inbox_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_index('ix_messages_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('webhook_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_excerpt', sa.String(length=1000), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('webhook_id', 'event_id', 'attempt_number', name='uq_webhook_delivery_attempt')
    )
    op.create_index(op.f('ix_webhook_deliveries_event_id'), 'webhook_deliveries', ['event_id'], unique=False)
    op.create_index('ix_webhook_deliveries_webhook_created', 'webhook_deliveries', ['webhook_id', 'created_at'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('message_id', sa.String(length=40), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_attachments_organization_id'), 'attachments', ['organization_id'], unique=False)
    op.create_index('ix_attachments_status_expires', 'attachments', ['status', 'expires_at'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('message_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_account_id', sa.String(length=40), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_message_id'), 'delivery_attempts', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_attempts_message_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index('ix_attachments_status_expires', table_name='attachments')
    op.drop_index(op.f('ix_attachments_organization_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_webhook_deliveries_webhook_created', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_event_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index('ix_messages_thread_created', table_name='messages')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index('ix_messages_inbox_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_webhooks_organization_id'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_threads_subject_normalized'), table_name='threads')
    op.drop_index(op.f('ix_threads_organization_id'), table_name='threads')
    op.drop_index('ix_threads_inbox_last', table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_inbound_ingests_organization_id'), table_name='inbound_ingests')
    op.drop_table('inbound_ingests')
    op.drop_index('ix_inboxes_org_status', table_name='inboxes')
    op.drop_index('ix_inboxes_expires_active', table_name='inboxes', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_inboxes_address_active', table_name='inboxes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('inboxes')
    op.drop_index(op.f('ix_provider_accounts_organization_id'), table_name='provider_accounts')
    op.drop_table('provider_accounts')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index('ix_events_resource_created', table_name='events')
    op.drop_index('ix_events_org_created', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_domains_organization_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('organizations')
    op.drop_index('ix_jobs_status_run_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
