"""domains verification columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-01 22:42:46.373664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('domains', sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('domains', sa.Column('check_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('domains', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'deleted_at')
    op.drop_column('domains', 'check_results')
    op.drop_column('domains', 'next_check_at')
    op.drop_column('domains', 'last_checked_at')
    # ### end Alembic commands ###
