"""governance tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-01 22:48:50.128343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppressions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_suppressions_org_email')
    )
    op.create_index(op.f('ix_suppressions_organization_id'), 'suppressions', ['organization_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('match', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_account_id', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['provider_account_id'], ['provider_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_organization_id'), 'routing_rules', ['organization_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('inbox_id', sa.String(length=40), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inbox_id'], ['inboxes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policies_inbox', 'policies', ['organization_id', 'inbox_id'], unique=True, postgresql_where=sa.text('inbox_id IS NOT NULL'))
    op.create_index('ix_policies_org_level', 'policies', ['organization_id'], unique=True, postgresql_where=sa.text('inbox_id IS NULL'))
    op.add_column('provider_accounts', sa.Column('webhook_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_provider_accounts_webhook_token', 'provider_accounts', ['webhook_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE provider_accounts DROP CONSTRAINT IF EXISTS uq_provider_accounts_webhook_token")
    op.execute("ALTER TABLE provider_accounts DROP CONSTRAINT IF EXISTS provider_accounts_webhook_token_key")
    op.drop_column('provider_accounts', 'webhook_token')
    op.drop_index('ix_policies_org_level', table_name='policies', postgresql_where=sa.text('inbox_id IS NULL'))
    op.drop_index('ix_policies_inbox', table_name='policies', postgresql_where=sa.text('inbox_id IS NOT NULL'))
    op.drop_table('policies')
    op.drop_index(op.f('ix_routing_rules_organization_id'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_suppressions_organization_id'), table_name='suppressions')
    op.drop_table('suppressions')
    # ### end Alembic commands ###
