"""usage daily

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-01 23:00:40.943530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('active_inboxes', sa.Integer(), nullable=False),
    sa.Column('ephemeral_inboxes_created', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('messages_received', sa.Integer(), nullable=False),
    sa.Column('attachment_bytes_stored', sa.BigInteger(), nullable=False),
    sa.Column('webhook_attempts', sa.Integer(), nullable=False),
    sa.Column('custom_domains', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'day', name='uq_usage_daily_org_day')
    )
    op.create_index(op.f('ix_usage_daily_organization_id'), 'usage_daily', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_daily_organization_id'), table_name='usage_daily')
    op.drop_table('usage_daily')
    # ### end Alembic commands ###
